config/routes.rb
Rails.application.routes.draw do

  resources :organizations do
    resources :business_units
    member do
      post 'create_business_unit'
    end
  end
  
  resources :business_units
  resources :surveys
  
  devise_for :companies

  root "welcome#index"
  get 'demo/index'
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base

	belongs_to :response
	belongs_to :survey
    belongs_to :question

end

app/models/business_unit.rb
class BusinessUnit < ActiveRecord::Base

  belongs_to :organization
  has_many :responses

  has_many :deployments
  has_many :surveys, :through => :deployments

end

app/models/company.rb
class Company < ActiveRecord::Base
  
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/deployment.rb
class Deployment < ActiveRecord::Base

  belongs_to :survey
  belongs_to :business_unit

end

app/models/option.rb
class Option < ActiveRecord::Base

	belongs_to :question

end

app/models/organization.rb
class Organization < ActiveRecord::Base

	has_many :business_units
	accepts_nested_attributes_for :business_units


	validates_uniqueness_of :name_legal


end

app/models/question.rb
class Question < ActiveRecord::Base
	
	has_many :options
	has_many :survey_questions
	has_many :surveys, :through => :survey_questions
	has_many :answers

end

app/models/response.rb
class Response < ActiveRecord::Base

	belongs_to :business_unit
	belongs_to :survey
	has_many :answers

end

app/models/survey.rb
class Survey < ActiveRecord::Base

	has_many :deployments
	has_many :business_units, :through => :deployments
	has_many :responses
	
	has_many :survey_questions
	has_many :questions, :through => :survey_questions
	
	has_many :answers

end

app/models/survey_question.rb
class SurveyQuestion < ActiveRecord::Base

  belongs_to :survey
  belongs_to :question

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # devise authentication to permit user to see the page:
  # before_action :authenticate_company!

end

app/controllers/business_units_controller.rb
class BusinessUnitsController < ApplicationController
  def index
    @business_units = BusinessUnit.all
  end

  def show
    @organization = Organization.find(params[:organization_id])
    @business_unit = BusinessUnit.find(params[:id])
  end

  def new
    @business_unit = BusinessUnit.new({:name => "Default", :organization_id => params[:organization_id]})
  end

  def create
    @business_unit = BusinessUnit.new(business_unit_params)

    respond_to do |format|
      if @business_unit.save
        format.html { redirect_to @business_unit, notice: 'Business Unit was successfully created.' }
        format.json { render :show, status: :created, location: @business_unit }
      else
        format.html { render :new }
        format.json { render json: @business_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @business_unit = BusinessUnit.find(params[:id])
  end

  def update
    respond_to do |format|
      if @business_unit.update(business_unit_params)
        format.html { redirect_to @business_unit, notice: 'Business Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_unit }
      else
        format.html { render :edit }
        format.json { render json: @business_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @business_unit = BusinessUnit.find(params[:id])
  end


  def destroy
    @organization = Organization.find(params[:organization_id])
    @business_unit = BusinessUnit.find(params[:id]).destroy
    flash[:notice] = "Business Unit destroyed successfully."
    redirect_to @organization
  end

  private

    def business_unit_params
      params.require(:business_unit).permit(:organization_id, :name, :industry)
    end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout false

  def index
  end

  def hello
  	#render('index')
  	@array = [1,2,3,4,5]
  	@id = params['id']
  	@page = params[:page].to_i
  end

  def other_hello
  	redirect_to(:controller => 'demo', :action => 'index')
  end

  def lynda
  	redirect_to("http://lynda.com")
  end


end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @business_unit = BusinessUnit.new
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_business_unit
    @organization = Organization.find(params[:id])
    @business_unit = @organization.business_units.build(business_unit_params)
    if @business_unit.save
      @business_unit = BusinessUnit.new
    end
    render :action => :show
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params[:organization].permit(:name_legal, :name_informal, :industry, business_unit: [:name, :industry])
    end

    def business_unit_params
      params[:business_unit].permit(:name, :industry)
    end


end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
  	@survey = Survey.all
  end

  def show
  end

  def delete
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_units_helper.rb
module BusinessUnitsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/business_units/_form.html.erb
<%= form_for(@business_unit) do |f| %>
  <% if @business_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_unit.errors.count, "error") %> prohibited this business unit from being saved:</h2>

      <ul>
      <% @business_unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table summary="Business Unit form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Industry</th>
        <td><%= f.text_field(:industry) %></td>
      </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/business_units/delete.html.erb
<h1>BusinessUnits#delete</h1>
<p>Find me in app/views/business_units/delete.html.erb</p>

app/views/business_units/edit.html.erb
<h1>BusinessUnits#edit</h1>
<p>Find me in app/views/business_units/edit.html.erb</p>

app/views/business_units/index.html.erb
<h1>BusinessUnits#index</h1>
<p>Find me in app/views/business_units/index.html.erb</p>

app/views/business_units/new.html.erb
<h1>New Business Unit</h1>

<%= render 'form' %>

<%= link_to 'Back', business_units_path %>

<%= params.inspect %>

app/views/business_units/show.html.erb
<h3><%= @organization.name_informal %></h1>
<h1><%= @business_unit.name %></h1>
<p>Total Responses: <%= @business_unit.responses.count %></p>

<%= params.inspect %>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table summary="Organization form fields">
      <tr>
        <th>Legal Name</th>
        <td><%= f.text_field(:name_legal) %></td>
      </tr>
      <tr>
        <th>Informal Name</th>
        <td><%= f.text_field(:name_informal) %></td>
      </tr>
      <tr>
        <th>Industry</th>
        <td><%= f.text_field(:industry) %></td>
      </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name_legal %></td>
        <td><%= organization.name_informal %></td>
        <td><%= organization.industry %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

<div class="organizations show">
  	<h2><%= @organization.name_informal %></h2>

  	<table summary="Organization Detail View">
	  	<tr>
	      	<th>ID</th>
	      	<td><%= @organization.id %></td>
	    </tr>
	    <tr>
	      	<th>Legal Name</th>
	      	<td><%= @organization.name_legal %></td>
	    </tr>
	    <tr>
	    	<th>Informal Name</th>
	    	<td><%= @organization.name_informal %></td>
	    </tr>
	    <tr>
	    	<th>Created</th>
	    	<td><%= @organization.created_at %></td>
	    </tr>
	    <tr>
	    	<th>Updated</th>
	    	<td><%= @organization.updated_at %></td>
	    </tr>
	</table>

	<br/><br/>

	<table class="listing" summary="Business Unit list">
	  	<tr class="header">
	  	  <th>ID</th>
	  	  <th>Business Unit</th>
	  	  <th>Industry</th>
	  	  <th>Actions</th>
	  	</tr>

		<% @organization.business_units.each do |business_unit| %>
		  	<tr>
		  	  <td><%= business_unit.id %></td>
		  	  <td><%= business_unit.name %></td>
		  	  <td><%= business_unit.industry %></td>
		  	  <td class="actions">
		  	  	<%= link_to("Show", organization_business_unit_path(@organization, business_unit), :class => 'action show') %>
		  	  	<%= link_to("Edit", '#', :class => 'action edit') %>
		  	  	<%= link_to("Delete", organization_business_unit_path(@organization, business_unit), :method => "delete", data: { confirm: 'Are you sure you want to delete this business unit?' }, :class => 'action delete') %>
		  	  </td>
		  	</tr>
		<% end %>
	</table>

	<%= form_for @business_unit, :url => create_business_unit_organization_path(@organization) do |f| %>
		  <table summary="Business Unit form fields">
		      <tr>
		        <th>Name</th>
		        <td><%= f.text_field(:name) %></td>
		      </tr>
		      <tr>
		        <th>Industry</th>
		        <td><%= f.text_field(:industry) %></td>
		      </tr>
		  </table>

		  <div class="actions">
		    <%= f.submit %>
		  </div>

	<% end %>


</div>

app/views/surveys/delete.html.erb
<h1>Survey#delete</h1>
<p>Find me in app/views/survey/delete.html.erb</p>

app/views/surveys/destroy.html.erb
<h1>Survey#destroy</h1>
<p>Find me in app/views/survey/destroy.html.erb</p>

app/views/surveys/index.html.erb
<h1>All C-Delta Surveys</h1>

<table>
  <thead>
    <tr>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <tr class="header">
      <th>Survey Name</th>
      <th>Active</th>
      <th>Created</th>
      <th>Updated</th>
      <th>Actions</th>
    </tr>
    <% @survey.each do |s| %>
      <tr>
        <td><%= s.survey_name %></td>
        <td><%= s.is_active %></td>
        <td><%= s.created_at %></td>
        <td><%= s.updated_at %></td>
        <td>
          <%= link_to 'Show', s %>
          <%= link_to 'Destroy', s, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/surveys/show.html.erb
<h1>Survey#show</h1>
<p>Find me in app/views/survey/show.html.erb</p>